# -*- coding: utf-8 -*-
"""NEWSscrapping

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10W7wEfjBUgZgd-_sHFHTGifyIsUVc7ad
"""

"""
A Python script that scrapes the headlines from the Kathmandu Post news website and saves them to a text file.

Dependencies:
    - requests
    - bs4 (BeautifulSoup)
    - csv
    - datetime

Usage:
    - Set the URL of the news website
    - Run the script to get the HTML content
    - Parse the HTML content using Beautiful Soup
    - Find the HTML tags that contain the news headlines
    - Save the headlines to a text file

Output:
    - A text file named 'kathmandupost_headlines.txt' that contains the current date and time, followed by the list of headlines.

Example:
    - See usage instructions above.

"""

import requests
from bs4 import BeautifulSoup
import csv
import datetime as dt

# Set the URL of the news website
url = 'https://kathmandupost.com/'

# Send a request to get the HTML content
response = requests.get(url)

# Parse the HTML content using Beautiful Soup
soup = BeautifulSoup(response.text, 'html.parser')

# Find the HTML tags that contain the news headlines
headlines = soup.find_all("article")
headline_list = []
for i in headlines:
  headline_list.append(i.text)

#Removing white spaces
headLinee = []
for i in headline_list:
  headLinee.append(i.strip())

# Save the headLinee to a text file
with open('kathmandupost_headlines.txt', 'w',newline='') as file:
  
  # Write the current date and time to the file
  x = str(dt.datetime.now())
  file.write("Todays date : "+x+'\n')
  # file.write("\n\n")

  # Write the headlines to the file
  for i in headLinee:
    file.write(i + "\n")
    # file.write("\n\n")

